[samples] C# class to verify Java binding
If the C# bindings aren't generated, the build would fail with:

    Foo.cs(6,33): error CS0246: The type or namespace name 'GoogleGson' could not be found
    (are you missing a using directive or an assembly reference?)